### ISSUE TITLE
Design proposal

### ISSUE THREAD

**Issue by pavgra** [OHDSI/DataQualityDashboard#1]
## Background

OHDSI has collected comprehensive expertise in libraries development and today it is possible to outline several lessons learned so that we could stick to best patterns during the development of the DQ Dashboard.

Positive patterns:
- Back-end represented by SQL templates with absence or minimal dynamic SQL;
- Encapsulation of middle-tier logic into Java library so that it could be used by both R and Java web apps. Usage of rJava to utilize the Java library in R. E.g. [SqlRender](https://github.com/OHDSI/SqlRender), [FeatureExtraction](https://github.com/OHDSI/FeatureExtraction)
- Standardization of specifications / DTOs. [StandardizedAnalysisAPI](https://github.com/OHDSI/StandardizedAnalysisAPI)

Problematic patterns:
- Middle-tier logic just in R. This makes it impossible to re-use the code and bumps people to duplicate code when you want to implement the use-case in Java / other language. E.g.: Arachne duplicates logic of Achilles query execution and results assembly into JSONs.
- UI coded in R Shiny. The same issue - you cannot simply embed such UI into an existing web app. Only iframe would work. E.g. PLE / PLP viewers - their integration into Atlas would require separate R Server and complicated logic or code re-writing. Proposed solution: apply pattern similar to what's done at middle-tier - code UI in HTML and JS, wrap them into library and use that library in R Shiny via [htmlwidgets](http://www.htmlwidgets.org/)

### Use-cases
![image](https://user-images.githubusercontent.com/10010071/61060154-1acdea80-a3c8-11e9-8ad7-a0ea1f12e4bd.png)

### Components
![image](https://user-images.githubusercontent.com/10010071/61060188-27ead980-a3c8-11e9-9f35-152e08c351fc.png)

### Technology stack:
- SQL for analytics
- Java for middle-tier logic
- R with r Java to wrap Java library into R library
- UI in HTML and JS, [Vega library](https://vega.github.io/vega/) for visualizations and its JSON spec as standard for data exchange format
- [Htmlwidgets](http://www.htmlwidgets.org/) to use the HTML-JS-CSS in R and R Shiny

Discussed with @alondhe

**Comment by alondhe** [comment]
From our meeting this morning, I think we're going to take this approach. Thank you @pavgra for laying this out.

**Comment by pavgra** [comment]
Based on the business requirements from #5, #6, #7 below is the proposed class hierarchy:

![Check hierarchy](https://user-images.githubusercontent.com/10010071/61302021-17b17080-a7b3-11e9-8ffb-ad1a4b2e7220.png)

(names in *italic* mean abstract classes)

**Comment by pavgra** [comment]
## Configuration format

- Since there is no practical reason to preserve the checks hierarchy in configuration and it would only complicate the reading of the file, it is proposed to store the checks in the form of a flat list
- Since the configuration goes to be pretty long, it is reasonable to pick data format which reduces formatting overhead, proposed - YAML

Example:
```
checks:
  - type: TableRequiredCheck
    tableName: PERSON
  - type: FieldForeignKeyCheck
    tableName: PERSON
    fieldName: gender_concept_id
    fkTable: CONCEPT
    fkField: CONCEPT_ID
  - type: ConceptMeasurementGenderCheck
    conceptId: 44819108
    requiredGenderConceptId: 8507
```

**Comment by alondhe** [comment]
Hi @pavgra , for the FieldForeignKey checks, you've utilized multiple attributes that will answer multiple checks (check for the relationship to the concept_id field in the concept table, check for domain, check for class). 

Is it fair to say that perhaps we will need a linkage between those check objects and the derived checks?

For instance:

```
- type: FieldIsForeignKey
    subsetType:
      - FieldForeignKeyDomain # a derived check
      - FieldForeignKeyClass # a derived check
    tableName: person
    fieldName: gender_concept_id
    fkTable: concept
    fkField: concept_id
    domain: Gender
```

**Comment by pavgra** [comment]
@alondhe , honestly, I'm not sure whether the FieldForeignKeyDomainCheck can be derived from the FieldForeignKeyCheck and vice versa.

First, let me clarify what I mean by the term "derived": having results of a check #1 you can do a check #2 w/o additional database querying.

So, having results of the FieldForeignKeyCheck, which would be represented by two numbers - `count` and `proportion` of rows (not) passed the condition, you cannot really tell which part of the rows also matched a domain condition and which doesn't. You would need to store the `concept_id`-s which passed the first check as an intermediate result and then filter them by domain to get results of the second check. But that means that you'd need to pull a huge number of ids either into a temp table or the middle-tier memory and I really doubt whether it's going to be more performant than just running a separate query for the second check (which in most cases would be backed by index or columnar compression). The same logic works vice versa.

Compare it to the TableMontlyCountChangeThresholdCheck (ouch, what a name) which I've outlined as a derived check. Having results of the TableMontlyCountChangeCheck which are presented by counts for each month, you can easily go through the series and figure out where the diff between two nearby months exceeds a given threshold. No need for temp results or second DB query.

So, summarizing it, I think that the FieldForeignKeyCheck, FieldForeignKeyDomainCheck and FieldForeignKeyClassCheck are three separate standalone things. Happy to learn about a better solution.

**Comment by pavgra** [comment]
## Results format

Results, as described by the class diagram above, are presented by either a Measurement (`count` and `proportion` of rows (not) passed the check) or by a MeasurementSeries - the numbers partitioned by some interval. Therefore, a sufficient format could be described as:

```
results:
  - id: 1
    value:
      count: 123
      proportion: 0.34
  - id: 2
    value:
      - count: 10
        proportion: 0.1
      - count: 5
        proportion: 0.05
```
where `id` correlates with the appropriate check identifier.

Also, we'd need to know used checks' configuration to have sufficient info for the UI. This basically means that a copy of the config described in the `Configuration storage format` section would be passed to UI as well.

**Comment by alondhe** [comment]
After speaking with Patrick today, I think we will be adjusting the workflow slightly in that the excel file we've been discussing will become a standard artifact of every CDM spec release. We are to use that as an input, but we can transform it into YAML first. To that end, our YAML representation of the reference set should be something that can be programmatically created. 

Regarding the results, we will need to produce SQL tables that are easy to query against as a SQL user, and the query needed to pull up the offending records should be made available. 

| check_name | table_name | field_name | check_status | context | category | subcategory | sql |
| ------------------|------------------|------------------|------------------|------------------|------------------|------------------|------------------|

**Comment by pavgra** [comment]
So, if we are going to store the `offending records` I don't think that anything changes regarding my message on derived checks. The FieldForeignKeyDomainCheck and FieldForeignKeyClassCheck still won't be able to derive results just based on FieldForeignKeyCheck offending records.

The only thing which additionally comes to my mind is to add "Top 10" violating records to each check result (in the JSON / YAML results file). I believe that could be useful. Something like:

```
results:
  - id: 1
    value:
      count: 123
      proportion: 0.34
    sample:
      - col1,col2,col3,col4
      - col1,col2,col3,col4
```

**Comment by alondhe** [comment]
> The FieldForeignKeyDomainCheck and FieldForeignKeyClassCheck still won't be able to derive results just based on FieldForeignKeyCheck offending records.

Regarding this point: what I was referring to in my first comment was that if we are to keep these as independent checks, then the check objects probably shouldn't have all FK-related attributes, but rather just the attributes needed for that check.

> The only thing which additionally comes to my mind is to add "Top 10" violating records to each check result (in the JSON / YAML results file). I believe that could be useful. Something like:

The offending records discussion from Patrick was that we should:

1. Show the distinct offending items in the app (e.g. here's the missing foreign keys, here's the concepts with implausible gender)
2. Give users the SQL from the check that allows the power users to be able to go an run it interactively to hopefully learn what they need to do to resolve the issue

**Comment by pavgra** [comment]
> Regarding this point: what I was referring to in my first comment was that if we are to keep these as independent checks, then the check objects probably shouldn't have all FK-related attributes, but rather just the attributes needed for that check.

On the one side, I understand the desire, and it could be achieved by something like this:
```
checks:
  - id: 1
    type: FieldForeignKeyCheck
    tableName: PERSON
    fieldName: gender_concept_id
    fkTable: CONCEPT
    fkField: CONCEPT_ID
  - id: 2
    extends: 1
    type: FieldForeignKeyDomainCheck
    domain: Gender
```

On the other side, that makes it more difficult for a human to read and understand the file (same as for a machine)

**Comment by alondhe** [comment]
```
checks:
  - id: 1
    type: FieldForeignKeyCheck
    tableName: PERSON
    fieldName: gender_concept_id
    fkTable: CONCEPT
    fkField: CONCEPT_ID
     threshold: 90%
  - id: 2
    extends: 1
    type: FieldForeignKeyDomainCheck
    domain: Gender
     threshold: 90%
```

**Comment by alondhe** [comment]
**Workflow after Patrick's feedback and 5th dev call:**
1. Grab official CSVs - one per level, one for threshold, one for metadata
2. Transform CSV into internal DQ format (JSON)
3. Instantiate classes
4. Create SQLs programmatically
5. Execute SQLs
6. Write to SQL tables in results schema and to JSON format

**Comment by alondhe** [comment]
**Specification Format**

```
reference:
  - type: TableRequiredCheck
    description: lorem $1 ipsum
    context: ...
    category: ...
    subcategory: ...

checks:
  - id: 1 
    type: TableRequiredCheck
    tableName: PERSON
    threshold: 1
  - id: 2 
    type: FieldForeignKeyCheck
    tableName: PERSON
    fieldName: gender_concept_id
    fkTable: CONCEPT
    fkField: CONCEPT_ID
    threshold: 0.9
  - id: 3 
    type: FieldForeignKeyDomainCheck
    tableName: PERSON
    fieldName: gender_concept_id
    fkTable: CONCEPT
    fkField: CONCEPT_ID
    fkDomain: Gender
    threshold: 0.95
  - id: 4 
    type: ConceptMeasurementGenderCheck
    conceptId: 44819108
    requiredGenderConceptId: 8507
    threshold: 0.7
```

**Comment by alondhe** [comment]
**Result Format**
```
results:
  - id: 1
    value:
      count: 123
      proportion: 0.34
- id: 2
    value:
      - startDate: '2015-01-01'
        endDate: '2015-01-31'
        count: 10
        proportion: 0.1
      - startDate: '2016-01-01'
        endDate: '2016-01-31'
        count: 5
        proportion: 0.05
```

**Comment by pavgra** [comment]
## htmlwidgets POC

Htmlwidgets website provides a nice tutorial on building a new component (library) - http://www.htmlwidgets.org/develop_intro.html

To validate the approach it was decided to build a sample [web component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) and utilize it both from a regular web page and R.

### Web Component

Define a web component in `dqDashboardComponent.js`:
```
const RESULTS_ATTR = 'data-results';

class DqDashboard extends HTMLElement {

  static getTemplate() {
    return `
      <h1>
        Dashboard
      </h1>
      <h2>
        Checks
      </h2>
      <div>
        Passed: {{passed}} / {{total}}
      </div>
    `
  };

  connectedCallback() {    
    this.root = this.attachShadow({mode: 'open'});
    this.render();
  }

  static get observedAttributes() {
    return [RESULTS_ATTR];
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (this.root && oldValue !== newValue) {
      this.render();
    }
  }

  get results() {
    return JSON.parse(this.getAttribute(RESULTS_ATTR));
  }

  render() {
    if (!this.results)
      return;

    const hbTemplate = Handlebars.compile(DqDashboard.getTemplate());
    const html = hbTemplate(this.results);
    this.root.innerHTML = html;
  }
}

customElements.define('dq-dashboard', DqDashboard);
```

### R

All boilerplate code creation can be easily handled by `htmlwidgets` functions:
```
library(devtools)
devtools::create("dqDashPOC")
setwd("./dqDashPOC")
htmlwidgets::scaffoldWidget("dqDashPOC")
```

From there, it is required to tweak a connector between R and JS located at `R/dqDashPOC.R` and replace entry function with:
```
dqDashPOC <- function(data, width = NULL, height = NULL, elementId = NULL) {
  htmlwidgets::createWidget(
    name = 'dqDashPOC',
    data,
    width = width,
    height = height,
    package = 'dqDashPOC',
    elementId = elementId
  )
}
```

Add dependencies `dqDashboardComponent.js` and [handlebars-latest.js](http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-latest.js) into `/inst/htmlwidgets/lib` and describe them in `/inst/htmlwidgets/dqDashPOC.yaml`:
```
dependencies:
  - name: dashboard
    version: 0.0.1
    src: htmlwidgets/lib
    script:
      - handlebars-latest.js
      - dqDashboardComponent.js
```

And define htmlwidget JS in `/inst/htmlwidgets/dqDashPOC.js` which will render the web component:
```
HTMLWidgets.widget({
  name: 'dqDashPOC',
  type: 'output',
  factory: function(el, width, height) {
    return {
      renderValue: function(data) {
        el.innerHTML = `<dq-dashboard data-results='${JSON.stringify(data)}'></dq-dashboard>`;
      },
      resize: function(width, height) {
        // TODO: code to re-render the widget with a new size
      }
    };
  }
});
```

That's it, next we just build and call the library:
```
library(dqDashPOC)
dqDashPOC(list(
  total = 10,
  passed = 7
))
```

And we get:
![image](https://user-images.githubusercontent.com/10010071/61496776-3e2a0400-a98b-11e9-98d8-946e6de7d16f.png)


### HTML

A simple webpage utilizing the same web component and giving the same output:
```
<html>
  <head>
		<script src="handlebars-latest.js"></script>
		<script src="dqDashboardComponent.js"></script>
  </head>
  <body>
    <dq-dashboard data-results='{ "passed": 7, "total": 10 }'></dq-dashboard>
  </body>
</html>
```
